global:
  scrape_interval:     15s
  external_labels:
    monitor: 'railway-prom'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'demo_application'
    scrape_interval: 5s
    static_configs:
      - targets: ['demo.do.prometheus.io:9090']
      
  - job_name: 'fastapi'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['fuckme-staging.up.railway.app']
